base:
  role: "full_node"
  data_dir: "/opt/aptos/data"
  waypoint:
    from_config: "0:683185844ef67e5c8eeaa158e635de2a4c574ce7907c4d4e71a6de688241c36e"

execution:
  genesis_file_location: "/opt/aptos/genesis/genesis.blob"
  concurrency_level: 8

storage:
  enable_indexer: true
  storage_pruner_config:
    pruning_window: 100000

full_node_networks:
- network_id: "public"
  discovery_method: "onchain"
  listen_address: "/ip4/0.0.0.0/tcp/6180"
